"""mensaje de tu migración

Revision ID: 03e7be7c24d3
Revises: c5c0269ce8f8
Create Date: 2026-06-19 19:42:27.908827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e7be7c24d3'
down_revision: Union[str, None] = 'c5c0269ce8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
