"""mensaje de tu migración

Revision ID: 44632984f609
Revises: 
Create Date: 2026-06-19 19:38:49.685762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44632984f609'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_admins_id', 'admins', ['id'], unique=False)
    op.create_index('ix_admins_username', 'admins', ['username'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='categories_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_parent', 'categories', ['parent_id'], unique=False)
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.create_index('ix_categories_slug', 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='addresses_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_addresses_id', 'addresses', ['id'], unique=False)
    op.create_index('ix_addresses_user_id', 'addresses', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('shipping_address', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_table('product_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='product_templates_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_templates_category_id', 'product_templates', ['category_id'], unique=False)
    op.create_index('ix_product_templates_id', 'product_templates', ['id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'pending', 'suspended', name='store_status'), nullable=True),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_status', 'stores', ['status'], unique=False)
    op.create_index('ix_stores_email', 'stores', ['email'], unique=True)
    op.create_index('ix_stores_id', 'stores', ['id'], unique=False)
    op.create_table('delivery_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='delivery_codes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('ix_delivery_codes_id', 'delivery_codes', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_product_category', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='products_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_product_category', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_index('ix_products_store_id', 'products', ['store_id'], unique=False)
    op.create_table('store_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('products_published', sa.Integer(), nullable=True),
    sa.Column('orders_delivered', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('chat_sessions', sa.Integer(), nullable=True),
    sa.Column('template_usage', sa.Integer(), nullable=True),
    sa.Column('new_users', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='store_metrics_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_store_metrics_date', 'store_metrics', ['date'], unique=False)
    op.create_index('ix_store_metrics_id', 'store_metrics', ['id'], unique=False)
    op.create_index('ix_store_metrics_store_id', 'store_metrics', ['store_id'], unique=False)
    op.create_table('template_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('field_label', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Integer(), nullable=True),
    sa.Column('placeholder', sa.String(length=200), nullable=True),
    sa.Column('validation_regex', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], name='template_fields_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_template_fields_id', 'template_fields', ['id'], unique=False)
    op.create_index('ix_template_fields_template_id', 'template_fields', ['template_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='chats_ibfk_1'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='chats_ibfk_4'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='chats_ibfk_3'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='chats_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chats_buyer_id', 'chats', ['buyer_id'], unique=False)
    op.create_index('ix_chats_id', 'chats', ['id'], unique=False)
    op.create_index('ix_chats_order_id', 'chats', ['order_id'], unique=False)
    op.create_index('ix_chats_product_id', 'chats', ['product_id'], unique=False)
    op.create_index('ix_chats_seller_id', 'chats', ['seller_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='messages_ibfk_1'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='messages_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_chat_id', 'messages', ['chat_id'], unique=False)
    op.create_index('ix_messages_id', 'messages', ['id'], unique=False)
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.drop_index('ix_messages_id', table_name='messages')
    op.drop_index('ix_messages_chat_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_chats_seller_id', table_name='chats')
    op.drop_index('ix_chats_product_id', table_name='chats')
    op.drop_index('ix_chats_order_id', table_name='chats')
    op.drop_index('ix_chats_id', table_name='chats')
    op.drop_index('ix_chats_buyer_id', table_name='chats')
    op.drop_table('chats')
    op.drop_index('ix_template_fields_template_id', table_name='template_fields')
    op.drop_index('ix_template_fields_id', table_name='template_fields')
    op.drop_table('template_fields')
    op.drop_index('ix_store_metrics_store_id', table_name='store_metrics')
    op.drop_index('ix_store_metrics_id', table_name='store_metrics')
    op.drop_index('ix_store_metrics_date', table_name='store_metrics')
    op.drop_table('store_metrics')
    op.drop_index('ix_products_store_id', table_name='products')
    op.drop_index('ix_products_id', table_name='products')
    op.drop_index('fk_product_category', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_delivery_codes_id', table_name='delivery_codes')
    op.drop_table('delivery_codes')
    op.drop_index('ix_stores_id', table_name='stores')
    op.drop_index('ix_stores_email', table_name='stores')
    op.drop_index('idx_status', table_name='stores')
    op.drop_table('stores')
    op.drop_index('ix_product_templates_id', table_name='product_templates')
    op.drop_index('ix_product_templates_category_id', table_name='product_templates')
    op.drop_table('product_templates')
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_addresses_user_id', table_name='addresses')
    op.drop_index('ix_addresses_id', table_name='addresses')
    op.drop_table('addresses')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_categories_slug', table_name='categories')
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_index('idx_parent', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_admins_username', table_name='admins')
    op.drop_index('ix_admins_id', table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
