"""auto_migration_20260702_082220

Revision ID: 859e5c0d217b
Revises: 04ca8d3c05e3
Create Date: 2026-07-02 08:22:21.529200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '859e5c0d217b'
down_revision: Union[str, None] = '04ca8d3c05e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_inquiries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='store_inquiries_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_store_inquiries_id', 'store_inquiries', ['id'], unique=False)
    op.create_index('ix_store_inquiries_store_id', 'store_inquiries', ['store_id'], unique=False)
    op.alter_column('chats', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('ix_store_inquiries_store_id', table_name='store_inquiries')
    op.drop_index('ix_store_inquiries_id', table_name='store_inquiries')
    op.drop_table('store_inquiries')
    # ### end Alembic commands ###
